version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    depends_on:
      - mongodb

volumes:
  mongodb_data:
    driver: local